-- Backfill additional customer metadata paths introduced by newer Kiwify payloads
update public.approved_sales
set
  role = coalesce(nullif(btrim(role), ''),
    nullif(btrim(payload->>'sale_type'), ''),
    nullif(btrim(payload->>'saleType'), ''),
    nullif(btrim(payload#>>'{data,sale_type}'), ''),
    nullif(btrim(payload#>>'{data,saleType}'), ''),
    nullif(btrim(payload#>>'{data,order,sale_type}'), ''),
    nullif(btrim(payload#>>'{data,order,saleType}'), ''),
    nullif(btrim(payload#>>'{Sale,sale_type}'), ''),
    nullif(btrim(payload#>>'{Sale,saleType}'), '')
  ),
  customer_phone = coalesce(nullif(btrim(customer_phone), ''),
    nullif(btrim(payload#>>'{customer,mobile}'), ''),
    nullif(btrim(payload#>>'{customer,mobile_phone}'), ''),
    nullif(btrim(payload#>>'{customer,mobilePhone}'), ''),
    nullif(btrim(payload#>>'{customer,mobile_number}'), ''),
    nullif(btrim(payload#>>'{customer,mobilePhoneNumber}'), ''),
    nullif(btrim(payload#>>'{Customer,mobile}'), ''),
    nullif(btrim(payload#>>'{Customer,mobile_phone}'), ''),
    nullif(btrim(payload#>>'{Customer,mobileNumber}'), ''),
    nullif(btrim(payload#>>'{Customer,mobile_number}'), ''),
    nullif(btrim(payload#>>'{Customer,mobilePhoneNumber}'), ''),
    nullif(btrim(payload#>>'{data,customer,mobile}'), ''),
    nullif(btrim(payload#>>'{data,customer,mobile_phone}'), ''),
    nullif(btrim(payload#>>'{data,customer,mobileNumber}'), ''),
    nullif(btrim(payload#>>'{data,customer,mobile_number}'), ''),
    nullif(btrim(payload#>>'{data,customer,mobilePhoneNumber}'), ''),
    nullif(btrim(payload#>>'{data,order,customer,mobile}'), ''),
    nullif(btrim(payload#>>'{data,order,customer,mobile_phone}'), ''),
    nullif(btrim(payload#>>'{data,order,customer,mobileNumber}'), ''),
    nullif(btrim(payload#>>'{data,order,customer,mobile_number}'), ''),
    nullif(btrim(payload#>>'{data,order,customer,mobilePhoneNumber}'), ''),
    nullif(btrim(payload#>>'{buyer,mobile}'), ''),
    nullif(btrim(payload#>>'{buyer,mobile_phone}'), ''),
    nullif(btrim(payload#>>'{buyer,mobileNumber}'), ''),
    nullif(btrim(payload#>>'{buyer,mobile_number}'), ''),
    nullif(btrim(payload#>>'{buyer,mobilePhoneNumber}'), ''),
    nullif(btrim(payload#>>'{data,buyer,mobile}'), ''),
    nullif(btrim(payload#>>'{data,buyer,mobile_phone}'), ''),
    nullif(btrim(payload#>>'{data,buyer,mobileNumber}'), ''),
    nullif(btrim(payload#>>'{data,buyer,mobile_number}'), ''),
    nullif(btrim(payload#>>'{data,buyer,mobilePhoneNumber}'), '')
  ),
  customer_document = coalesce(nullif(btrim(customer_document), ''),
    nullif(btrim(payload#>>'{customer,CPF}'), ''),
    nullif(btrim(payload#>>'{customer,CNPJ}'), ''),
    nullif(btrim(payload#>>'{Customer,CPF}'), ''),
    nullif(btrim(payload#>>'{Customer,CNPJ}'), ''),
    nullif(btrim(payload#>>'{data,customer,CPF}'), ''),
    nullif(btrim(payload#>>'{data,customer,CNPJ}'), ''),
    nullif(btrim(payload#>>'{data,order,customer,CPF}'), ''),
    nullif(btrim(payload#>>'{data,order,customer,CNPJ}'), ''),
    nullif(btrim(payload#>>'{buyer,CPF}'), ''),
    nullif(btrim(payload#>>'{buyer,CNPJ}'), ''),
    nullif(btrim(payload#>>'{data,buyer,CPF}'), ''),
    nullif(btrim(payload#>>'{data,buyer,CNPJ}'), '')
  ),
  utm_source = coalesce(nullif(btrim(utm_source), ''),
    nullif(btrim(payload#>>'{TrackingParameters,utm_source}'), ''),
    nullif(btrim(payload#>>'{TrackingParameters,utmSource}'), ''),
    nullif(btrim(payload#>>'{trackingParameters,utm_source}'), ''),
    nullif(btrim(payload#>>'{trackingParameters,utmSource}'), '')
  ),
  utm_medium = coalesce(nullif(btrim(utm_medium), ''),
    nullif(btrim(payload#>>'{TrackingParameters,utm_medium}'), ''),
    nullif(btrim(payload#>>'{TrackingParameters,utmMedium}'), ''),
    nullif(btrim(payload#>>'{trackingParameters,utm_medium}'), ''),
    nullif(btrim(payload#>>'{trackingParameters,utmMedium}'), '')
  ),
  utm_campaign = coalesce(nullif(btrim(utm_campaign), ''),
    nullif(btrim(payload#>>'{TrackingParameters,utm_campaign}'), ''),
    nullif(btrim(payload#>>'{TrackingParameters,utmCampaign}'), ''),
    nullif(btrim(payload#>>'{trackingParameters,utm_campaign}'), ''),
    nullif(btrim(payload#>>'{trackingParameters,utmCampaign}'), '')
  );

update public.pending_payments
set
  role = coalesce(nullif(btrim(role), ''),
    nullif(btrim(payload->>'sale_type'), ''),
    nullif(btrim(payload->>'saleType'), ''),
    nullif(btrim(payload#>>'{data,sale_type}'), ''),
    nullif(btrim(payload#>>'{data,saleType}'), ''),
    nullif(btrim(payload#>>'{data,order,sale_type}'), ''),
    nullif(btrim(payload#>>'{data,order,saleType}'), ''),
    nullif(btrim(payload#>>'{Sale,sale_type}'), ''),
    nullif(btrim(payload#>>'{Sale,saleType}'), '')
  ),
  customer_phone = coalesce(nullif(btrim(customer_phone), ''),
    nullif(btrim(payload#>>'{customer,mobile}'), ''),
    nullif(btrim(payload#>>'{customer,mobile_phone}'), ''),
    nullif(btrim(payload#>>'{customer,mobilePhone}'), ''),
    nullif(btrim(payload#>>'{customer,mobile_number}'), ''),
    nullif(btrim(payload#>>'{customer,mobilePhoneNumber}'), ''),
    nullif(btrim(payload#>>'{Customer,mobile}'), ''),
    nullif(btrim(payload#>>'{Customer,mobile_phone}'), ''),
    nullif(btrim(payload#>>'{Customer,mobileNumber}'), ''),
    nullif(btrim(payload#>>'{Customer,mobile_number}'), ''),
    nullif(btrim(payload#>>'{Customer,mobilePhoneNumber}'), ''),
    nullif(btrim(payload#>>'{data,customer,mobile}'), ''),
    nullif(btrim(payload#>>'{data,customer,mobile_phone}'), ''),
    nullif(btrim(payload#>>'{data,customer,mobileNumber}'), ''),
    nullif(btrim(payload#>>'{data,customer,mobile_number}'), ''),
    nullif(btrim(payload#>>'{data,customer,mobilePhoneNumber}'), ''),
    nullif(btrim(payload#>>'{data,order,customer,mobile}'), ''),
    nullif(btrim(payload#>>'{data,order,customer,mobile_phone}'), ''),
    nullif(btrim(payload#>>'{data,order,customer,mobileNumber}'), ''),
    nullif(btrim(payload#>>'{data,order,customer,mobile_number}'), ''),
    nullif(btrim(payload#>>'{data,order,customer,mobilePhoneNumber}'), ''),
    nullif(btrim(payload#>>'{buyer,mobile}'), ''),
    nullif(btrim(payload#>>'{buyer,mobile_phone}'), ''),
    nullif(btrim(payload#>>'{buyer,mobileNumber}'), ''),
    nullif(btrim(payload#>>'{buyer,mobile_number}'), ''),
    nullif(btrim(payload#>>'{buyer,mobilePhoneNumber}'), ''),
    nullif(btrim(payload#>>'{data,buyer,mobile}'), ''),
    nullif(btrim(payload#>>'{data,buyer,mobile_phone}'), ''),
    nullif(btrim(payload#>>'{data,buyer,mobileNumber}'), ''),
    nullif(btrim(payload#>>'{data,buyer,mobile_number}'), ''),
    nullif(btrim(payload#>>'{data,buyer,mobilePhoneNumber}'), '')
  ),
  customer_document = coalesce(nullif(btrim(customer_document), ''),
    nullif(btrim(payload#>>'{customer,CPF}'), ''),
    nullif(btrim(payload#>>'{customer,CNPJ}'), ''),
    nullif(btrim(payload#>>'{Customer,CPF}'), ''),
    nullif(btrim(payload#>>'{Customer,CNPJ}'), ''),
    nullif(btrim(payload#>>'{data,customer,CPF}'), ''),
    nullif(btrim(payload#>>'{data,customer,CNPJ}'), ''),
    nullif(btrim(payload#>>'{data,order,customer,CPF}'), ''),
    nullif(btrim(payload#>>'{data,order,customer,CNPJ}'), ''),
    nullif(btrim(payload#>>'{buyer,CPF}'), ''),
    nullif(btrim(payload#>>'{buyer,CNPJ}'), ''),
    nullif(btrim(payload#>>'{data,buyer,CPF}'), ''),
    nullif(btrim(payload#>>'{data,buyer,CNPJ}'), '')
  ),
  utm_source = coalesce(nullif(btrim(utm_source), ''),
    nullif(btrim(payload#>>'{TrackingParameters,utm_source}'), ''),
    nullif(btrim(payload#>>'{TrackingParameters,utmSource}'), ''),
    nullif(btrim(payload#>>'{trackingParameters,utm_source}'), ''),
    nullif(btrim(payload#>>'{trackingParameters,utmSource}'), '')
  ),
  utm_medium = coalesce(nullif(btrim(utm_medium), ''),
    nullif(btrim(payload#>>'{TrackingParameters,utm_medium}'), ''),
    nullif(btrim(payload#>>'{TrackingParameters,utmMedium}'), ''),
    nullif(btrim(payload#>>'{trackingParameters,utm_medium}'), ''),
    nullif(btrim(payload#>>'{trackingParameters,utmMedium}'), '')
  ),
  utm_campaign = coalesce(nullif(btrim(utm_campaign), ''),
    nullif(btrim(payload#>>'{TrackingParameters,utm_campaign}'), ''),
    nullif(btrim(payload#>>'{TrackingParameters,utmCampaign}'), ''),
    nullif(btrim(payload#>>'{trackingParameters,utm_campaign}'), ''),
    nullif(btrim(payload#>>'{trackingParameters,utmCampaign}'), '')
  );

update public.rejected_payments
set
  role = coalesce(nullif(btrim(role), ''),
    nullif(btrim(payload->>'sale_type'), ''),
    nullif(btrim(payload->>'saleType'), ''),
    nullif(btrim(payload#>>'{data,sale_type}'), ''),
    nullif(btrim(payload#>>'{data,saleType}'), ''),
    nullif(btrim(payload#>>'{data,order,sale_type}'), ''),
    nullif(btrim(payload#>>'{data,order,saleType}'), ''),
    nullif(btrim(payload#>>'{Sale,sale_type}'), ''),
    nullif(btrim(payload#>>'{Sale,saleType}'), '')
  ),
  customer_phone = coalesce(nullif(btrim(customer_phone), ''),
    nullif(btrim(payload#>>'{customer,mobile}'), ''),
    nullif(btrim(payload#>>'{customer,mobile_phone}'), ''),
    nullif(btrim(payload#>>'{customer,mobilePhone}'), ''),
    nullif(btrim(payload#>>'{customer,mobile_number}'), ''),
    nullif(btrim(payload#>>'{customer,mobilePhoneNumber}'), ''),
    nullif(btrim(payload#>>'{Customer,mobile}'), ''),
    nullif(btrim(payload#>>'{Customer,mobile_phone}'), ''),
    nullif(btrim(payload#>>'{Customer,mobileNumber}'), ''),
    nullif(btrim(payload#>>'{Customer,mobile_number}'), ''),
    nullif(btrim(payload#>>'{Customer,mobilePhoneNumber}'), ''),
    nullif(btrim(payload#>>'{data,customer,mobile}'), ''),
    nullif(btrim(payload#>>'{data,customer,mobile_phone}'), ''),
    nullif(btrim(payload#>>'{data,customer,mobileNumber}'), ''),
    nullif(btrim(payload#>>'{data,customer,mobile_number}'), ''),
    nullif(btrim(payload#>>'{data,customer,mobilePhoneNumber}'), ''),
    nullif(btrim(payload#>>'{data,order,customer,mobile}'), ''),
    nullif(btrim(payload#>>'{data,order,customer,mobile_phone}'), ''),
    nullif(btrim(payload#>>'{data,order,customer,mobileNumber}'), ''),
    nullif(btrim(payload#>>'{data,order,customer,mobile_number}'), ''),
    nullif(btrim(payload#>>'{data,order,customer,mobilePhoneNumber}'), ''),
    nullif(btrim(payload#>>'{buyer,mobile}'), ''),
    nullif(btrim(payload#>>'{buyer,mobile_phone}'), ''),
    nullif(btrim(payload#>>'{buyer,mobileNumber}'), ''),
    nullif(btrim(payload#>>'{buyer,mobile_number}'), ''),
    nullif(btrim(payload#>>'{buyer,mobilePhoneNumber}'), ''),
    nullif(btrim(payload#>>'{data,buyer,mobile}'), ''),
    nullif(btrim(payload#>>'{data,buyer,mobile_phone}'), ''),
    nullif(btrim(payload#>>'{data,buyer,mobileNumber}'), ''),
    nullif(btrim(payload#>>'{data,buyer,mobile_number}'), ''),
    nullif(btrim(payload#>>'{data,buyer,mobilePhoneNumber}'), '')
  ),
  customer_document = coalesce(nullif(btrim(customer_document), ''),
    nullif(btrim(payload#>>'{customer,CPF}'), ''),
    nullif(btrim(payload#>>'{customer,CNPJ}'), ''),
    nullif(btrim(payload#>>'{Customer,CPF}'), ''),
    nullif(btrim(payload#>>'{Customer,CNPJ}'), ''),
    nullif(btrim(payload#>>'{data,customer,CPF}'), ''),
    nullif(btrim(payload#>>'{data,customer,CNPJ}'), ''),
    nullif(btrim(payload#>>'{data,order,customer,CPF}'), ''),
    nullif(btrim(payload#>>'{data,order,customer,CNPJ}'), ''),
    nullif(btrim(payload#>>'{buyer,CPF}'), ''),
    nullif(btrim(payload#>>'{buyer,CNPJ}'), ''),
    nullif(btrim(payload#>>'{data,buyer,CPF}'), ''),
    nullif(btrim(payload#>>'{data,buyer,CNPJ}'), '')
  ),
  utm_source = coalesce(nullif(btrim(utm_source), ''),
    nullif(btrim(payload#>>'{TrackingParameters,utm_source}'), ''),
    nullif(btrim(payload#>>'{TrackingParameters,utmSource}'), ''),
    nullif(btrim(payload#>>'{trackingParameters,utm_source}'), ''),
    nullif(btrim(payload#>>'{trackingParameters,utmSource}'), '')
  ),
  utm_medium = coalesce(nullif(btrim(utm_medium), ''),
    nullif(btrim(payload#>>'{TrackingParameters,utm_medium}'), ''),
    nullif(btrim(payload#>>'{TrackingParameters,utmMedium}'), ''),
    nullif(btrim(payload#>>'{trackingParameters,utm_medium}'), ''),
    nullif(btrim(payload#>>'{trackingParameters,utmMedium}'), '')
  ),
  utm_campaign = coalesce(nullif(btrim(utm_campaign), ''),
    nullif(btrim(payload#>>'{TrackingParameters,utm_campaign}'), ''),
    nullif(btrim(payload#>>'{TrackingParameters,utmCampaign}'), ''),
    nullif(btrim(payload#>>'{trackingParameters,utm_campaign}'), ''),
    nullif(btrim(payload#>>'{trackingParameters,utmCampaign}'), '')
  );

update public.refunded_sales
set
  role = coalesce(nullif(btrim(role), ''),
    nullif(btrim(payload->>'sale_type'), ''),
    nullif(btrim(payload->>'saleType'), ''),
    nullif(btrim(payload#>>'{data,sale_type}'), ''),
    nullif(btrim(payload#>>'{data,saleType}'), ''),
    nullif(btrim(payload#>>'{data,order,sale_type}'), ''),
    nullif(btrim(payload#>>'{data,order,saleType}'), ''),
    nullif(btrim(payload#>>'{Sale,sale_type}'), ''),
    nullif(btrim(payload#>>'{Sale,saleType}'), '')
  ),
  customer_phone = coalesce(nullif(btrim(customer_phone), ''),
    nullif(btrim(payload#>>'{customer,mobile}'), ''),
    nullif(btrim(payload#>>'{customer,mobile_phone}'), ''),
    nullif(btrim(payload#>>'{customer,mobilePhone}'), ''),
    nullif(btrim(payload#>>'{customer,mobile_number}'), ''),
    nullif(btrim(payload#>>'{customer,mobilePhoneNumber}'), ''),
    nullif(btrim(payload#>>'{Customer,mobile}'), ''),
    nullif(btrim(payload#>>'{Customer,mobile_phone}'), ''),
    nullif(btrim(payload#>>'{Customer,mobileNumber}'), ''),
    nullif(btrim(payload#>>'{Customer,mobile_number}'), ''),
    nullif(btrim(payload#>>'{Customer,mobilePhoneNumber}'), ''),
    nullif(btrim(payload#>>'{data,customer,mobile}'), ''),
    nullif(btrim(payload#>>'{data,customer,mobile_phone}'), ''),
    nullif(btrim(payload#>>'{data,customer,mobileNumber}'), ''),
    nullif(btrim(payload#>>'{data,customer,mobile_number}'), ''),
    nullif(btrim(payload#>>'{data,customer,mobilePhoneNumber}'), ''),
    nullif(btrim(payload#>>'{data,order,customer,mobile}'), ''),
    nullif(btrim(payload#>>'{data,order,customer,mobile_phone}'), ''),
    nullif(btrim(payload#>>'{data,order,customer,mobileNumber}'), ''),
    nullif(btrim(payload#>>'{data,order,customer,mobile_number}'), ''),
    nullif(btrim(payload#>>'{data,order,customer,mobilePhoneNumber}'), ''),
    nullif(btrim(payload#>>'{buyer,mobile}'), ''),
    nullif(btrim(payload#>>'{buyer,mobile_phone}'), ''),
    nullif(btrim(payload#>>'{buyer,mobileNumber}'), ''),
    nullif(btrim(payload#>>'{buyer,mobile_number}'), ''),
    nullif(btrim(payload#>>'{buyer,mobilePhoneNumber}'), ''),
    nullif(btrim(payload#>>'{data,buyer,mobile}'), ''),
    nullif(btrim(payload#>>'{data,buyer,mobile_phone}'), ''),
    nullif(btrim(payload#>>'{data,buyer,mobileNumber}'), ''),
    nullif(btrim(payload#>>'{data,buyer,mobile_number}'), ''),
    nullif(btrim(payload#>>'{data,buyer,mobilePhoneNumber}'), '')
  ),
  customer_document = coalesce(nullif(btrim(customer_document), ''),
    nullif(btrim(payload#>>'{customer,CPF}'), ''),
    nullif(btrim(payload#>>'{customer,CNPJ}'), ''),
    nullif(btrim(payload#>>'{Customer,CPF}'), ''),
    nullif(btrim(payload#>>'{Customer,CNPJ}'), ''),
    nullif(btrim(payload#>>'{data,customer,CPF}'), ''),
    nullif(btrim(payload#>>'{data,customer,CNPJ}'), ''),
    nullif(btrim(payload#>>'{data,order,customer,CPF}'), ''),
    nullif(btrim(payload#>>'{data,order,customer,CNPJ}'), ''),
    nullif(btrim(payload#>>'{buyer,CPF}'), ''),
    nullif(btrim(payload#>>'{buyer,CNPJ}'), ''),
    nullif(btrim(payload#>>'{data,buyer,CPF}'), ''),
    nullif(btrim(payload#>>'{data,buyer,CNPJ}'), '')
  ),
  utm_source = coalesce(nullif(btrim(utm_source), ''),
    nullif(btrim(payload#>>'{TrackingParameters,utm_source}'), ''),
    nullif(btrim(payload#>>'{TrackingParameters,utmSource}'), ''),
    nullif(btrim(payload#>>'{trackingParameters,utm_source}'), ''),
    nullif(btrim(payload#>>'{trackingParameters,utmSource}'), '')
  ),
  utm_medium = coalesce(nullif(btrim(utm_medium), ''),
    nullif(btrim(payload#>>'{TrackingParameters,utm_medium}'), ''),
    nullif(btrim(payload#>>'{TrackingParameters,utmMedium}'), ''),
    nullif(btrim(payload#>>'{trackingParameters,utm_medium}'), ''),
    nullif(btrim(payload#>>'{trackingParameters,utmMedium}'), '')
  ),
  utm_campaign = coalesce(nullif(btrim(utm_campaign), ''),
    nullif(btrim(payload#>>'{TrackingParameters,utm_campaign}'), ''),
    nullif(btrim(payload#>>'{TrackingParameters,utmCampaign}'), ''),
    nullif(btrim(payload#>>'{trackingParameters,utm_campaign}'), ''),
    nullif(btrim(payload#>>'{trackingParameters,utmCampaign}'), '')
  );
